#!/usr/bin/env bash
# Configure your Nginx server

sudo apt-get update -y
sudo apt-get install nginx -y
echo "Holberton School" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
new_string="server_name _;\n\trewrite ^\/redirect_me youtube.com permanent;"
second_string="\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}"
sed -i "s/server_name _;/$new_string$second_string/" /etc/nginx/sites-enabled/default
service nginx start
