#!/usr/bin/env bash
#output a sequence of numbers, replacing every multiple of 3 Fizz, every
#multiple of 5 with Buzz, and every multiple of both with FizzBuzz from 1 to 100

for i in {1..100}
do
    if (( i % 3 == 0 && i % 5 == 0))
    then
       echo "FizzBuzz"
    elif (( i % 5 == 0))
    then
    	 echo "Buzz"
    elif (( i % 3 == 0))
    then
    	 echo "Fizz"
    else
	echo "$i"
    fi
done
